######################################
# model settings 
######################################
model:
  dim_node_feat: 128
  num_heads: 4
  num_layers: 4
  dropout: 0.1
  num_node_feat: 12
  num_classes: 2
